export const CATEGORIES = [
  {
    name: "Bedsheets",
    name_fr: "Draps",
    slug: "bedsheets",
    description: "Double, triple and king bedsheet sets for everyday rest.",
    description_fr: "Draps 2, 3 et 4 places pour le quotidien.",
  },
  {
    name: "Pillowcases",
    name_fr: "Taies d’oreiller",
    slug: "pillowcases",
    description: "Pillowcases sold in sets with the house bedsheets.",
    description_fr: "Taies d’oreiller proposées avec les draps de la maison.",
  },
  {
    name: "Duvets",
    name_fr: "Couettes",
    slug: "duvets",
    description: "Duvets and complete bedding sets.",
    description_fr: "Couettes et ensembles de literie complets.",
  },
  {
    name: "Curtains",
    name_fr: "Rideaux",
    slug: "curtains",
    description: "Curtains, including 3-in-1 drapes for the living room and bedroom.",
    description_fr: "Rideaux, dont le rideau 3 en 1 pour le salon et la chambre.",
  },
  {
    name: "Mosquito nets",
    name_fr: "Moustiquaires",
    slug: "mosquito-nets",
    description: "Large and medium mosquito nets.",
    description_fr: "Moustiquaires grande et moyenne taille.",
  },
  {
    name: "Sofa covers",
    name_fr: "Housses de canapé",
    slug: "sofa-covers",
    description: "Sofa and chair covers that refresh a living room.",
    description_fr: "Housses de canapé et de chaises pour renouveler le salon.",
  },
  {
    name: "Mattress protectors",
    name_fr: "Protège-matelas",
    slug: "mattress-protectors",
    description: "Mattress protectors for double and triple beds.",
    description_fr: "Protège-matelas pour lits 2 et 3 places.",
  },
];

function tiers(rows) {
  return rows.map(([min_qty, max_qty, unit_price]) => ({ min_qty, max_qty, unit_price }));
}

function alts(name) {
  return [
    `${name} — main product photo`,
    `${name} — related photo, fabric and finish`,
    `${name} — related photo, set contents`,
  ];
}

export const PRODUCTS = [
  {
    slug: "double-plastic-bedsheet",
    name: "Double plastic bedsheet",
    name_fr: "Drap 2 places en plastique",
    category: "bedsheets",
    sku: "JHT-DRAP-2P-PLAST",
    featured: true,
    price: 4500,
    price_tiers: tiers([
      [1, 9, 4500],
      [10, 20, 4400],
      [21, 50, 4300],
      [51, 100, 4200],
      [101, 500, 4100],
      [501, null, 4000],
    ]),
    whats_included: "1 double plastic bedsheet.",
    whats_included_fr: "1 drap 2 places en plastique.",
    description: "A practical double bedsheet in plastic. Priced by quantity for the home and for wholesale.",
    description_fr: "Drap 2 places en plastique, pratique au quotidien. Prix dégressif selon la quantité.",
  },
  {
    slug: "double-bedsheet-in-bag",
    name: "Double bedsheet in bag",
    name_fr: "Drap 2 places en sac",
    category: "bedsheets",
    sku: "JHT-DRAP-2P-SAC",
    featured: true,
    price: 5000,
    price_tiers: tiers([
      [1, 9, 5000],
      [10, 20, 4700],
      [21, 50, 4600],
      [51, 100, 4500],
      [101, 500, 4400],
    ]),
    whats_included: "1 double bedsheet, packed in a bag.",
    whats_included_fr: "1 drap 2 places en sac.",
    description: "Double bedsheet packed in a bag. Better unit price as the quantity rises.",
    description_fr: "Drap 2 places livré en sac. Le prix unitaire baisse avec la quantité.",
  },
  {
    slug: "triple-bedsheet-2-pillowcases",
    name: "Triple bedsheet set with 2 pillowcases",
    name_fr: "Draps 3 places 2 taies",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-2T",
    featured: true,
    price: 6500,
    price_tiers: tiers([
      [1, 9, 6500],
      [10, 20, 6000],
      [21, 50, 5600],
      [51, 100, 5500],
      [101, 500, 5400],
    ]),
    whats_included: "Triple bedsheet set with 2 pillowcases.",
    whats_included_fr: "Draps 3 places avec 2 taies.",
    description: "A 3-place bedsheet set with two pillowcases.",
    description_fr: "Ensemble drap 3 places avec deux taies d’oreiller.",
  },
  {
    slug: "triple-flat-fitted-2-pillowcases",
    name: "Triple flat sheet, fitted sheet and 2 pillowcases",
    name_fr: "Draps 3 places un drap et un drap housse, 2 taies",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-HOUSSE-2T",
    featured: true,
    price: 6500,
    price_tiers: tiers([
      [1, 9, 6500],
      [10, 20, 6300],
      [21, 50, 6200],
      [51, 100, 6000],
      [101, 500, 5800],
    ]),
    whats_included: "1 flat sheet, 1 fitted sheet, 2 pillowcases — triple size.",
    whats_included_fr: "1 drap, 1 drap housse, 2 taies — 3 places.",
    description: "Complete triple bedding: a flat sheet, a fitted sheet and two pillowcases.",
    description_fr: "Literie 3 places complète : un drap, un drap housse et deux taies.",
  },
  {
    slug: "triple-sheet-2-pillowcases-2-curtains-essentiel",
    name: "Triple sheet, 2 pillowcases and 2 curtains",
    name_fr: "Draps 3 places 1 drap, 2 taies et 2 rideaux",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-2T-2R-ESS",
    featured: false,
    price: 5000,
    price_tiers: tiers([
      [1, 9, 5000],
      [10, 20, 4900],
      [21, 50, 4800],
      [51, 100, 4750],
      [101, 500, 4700],
    ]),
    whats_included: "1 triple sheet, 2 pillowcases and 2 curtains.",
    whats_included_fr: "1 drap 3 places, 2 taies et 2 rideaux.",
    description: "A triple sheet with two pillowcases and two curtains.",
    description_fr: "Un drap 3 places avec deux taies et deux rideaux.",
  },
  {
    slug: "triple-bedsheet-4-pillowcases",
    name: "Triple bedsheet set with 4 pillowcases",
    name_fr: "Draps 3 places 4 taies",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-4T",
    featured: true,
    price: 7500,
    price_tiers: tiers([
      [1, 9, 7500],
      [10, 20, 7000],
      [21, 50, 6800],
      [51, 100, 6700],
      [101, 500, 6500],
    ]),
    whats_included: "Triple bedsheet set with 4 pillowcases.",
    whats_included_fr: "Draps 3 places avec 4 taies.",
    description: "A 3-place bedsheet set finished with four pillowcases.",
    description_fr: "Ensemble drap 3 places avec quatre taies d’oreiller.",
  },
  {
    slug: "triple-bedsheet-2-pillowcases-2-curtains",
    name: "Triple bedsheet, 2 pillowcases and 2 curtains",
    name_fr: "Draps 3 places 2 taies avec 2 rideaux",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-2T-2R",
    featured: true,
    price: 9000,
    price_tiers: tiers([
      [1, 9, 9000],
      [10, 20, 8500],
      [21, 50, 8000],
      [51, 100, 7500],
      [101, 500, 7300],
    ]),
    whats_included: "Triple bedsheet, 2 pillowcases and 2 curtains.",
    whats_included_fr: "Draps 3 places, 2 taies et 2 rideaux.",
    description: "Triple bedding with two pillowcases and a pair of curtains.",
    description_fr: "Literie 3 places avec deux taies et une paire de rideaux.",
  },
  {
    slug: "triple-bedsheet-4-pillowcases-4-curtains",
    name: "Triple bedsheet, 4 pillowcases and 4 curtains",
    name_fr: "Draps 3 places 4 taies 4 rideaux",
    category: "bedsheets",
    sku: "JHT-DRAP-3P-4T-4R",
    featured: true,
    price: 12000,
    price_tiers: tiers([
      [1, 9, 12000],
      [10, 20, 11500],
      [21, 50, 11000],
      [51, 100, 10500],
      [101, 500, 10000],
    ]),
    whats_included: "Triple bedsheet, 4 pillowcases and 4 curtains.",
    whats_included_fr: "Draps 3 places, 4 taies et 4 rideaux.",
    description: "A full triple room set: bedsheet, four pillowcases and four curtains.",
    description_fr: "Ensemble chambre 3 places : drap, quatre taies et quatre rideaux.",
  },
  {
    slug: "king-bedsheet-2-pillowcases",
    name: "King bedsheet set with 2 pillowcases",
    name_fr: "Draps 4 places 2 taies",
    category: "bedsheets",
    sku: "JHT-DRAP-4P-2T",
    featured: true,
    price: 8500,
    price_tiers: tiers([
      [1, 9, 8500],
      [10, 20, 8000],
      [21, 50, 7600],
      [51, 100, 7500],
    ]),
    whats_included: "King (4-place) bedsheet set with 2 pillowcases.",
    whats_included_fr: "Draps 4 places avec 2 taies.",
    description: "A 4-place bedsheet set with two pillowcases.",
    description_fr: "Ensemble drap 4 places avec deux taies d’oreiller.",
  },
  {
    slug: "king-bedsheet-4-pillowcases",
    name: "King bedsheet set with 4 pillowcases",
    name_fr: "Draps 4 places 4 taies",
    category: "bedsheets",
    sku: "JHT-DRAP-4P-4T",
    featured: true,
    price: 11000,
    price_tiers: tiers([
      [1, 9, 11000],
      [10, 20, 10500],
      [21, 50, 10300],
      [51, 100, 10100],
      [101, 500, 10000],
      [501, null, 9800],
    ]),
    whats_included: "King (4-place) bedsheet set with 4 pillowcases.",
    whats_included_fr: "Draps 4 places avec 4 taies.",
    description: "A 4-place bedsheet set with four pillowcases. Best unit price from 501 pieces.",
    description_fr: "Ensemble drap 4 places avec quatre taies. Meilleur prix à partir de 501 pièces.",
  },
  {
    slug: "triple-duvet-2-sheets-4-pillowcases",
    name: "Triple duvet with 2 sheets and 4 pillowcases",
    name_fr: "Couette 3 places, 2 draps, 4 taies",
    category: "duvets",
    sku: "JHT-COUETTE-3P",
    featured: true,
    price: 18500,
    price_tiers: tiers([[1, null, 18500]]),
    whats_included: "1 triple duvet, 2 sheets and 4 pillowcases.",
    whats_included_fr: "1 couette 3 places, 2 draps et 4 taies.",
    description: "A complete triple duvet set with two sheets and four pillowcases.",
    description_fr: "Ensemble couette 3 places avec deux draps et quatre taies.",
  },
  {
    slug: "curtain-3-in-1",
    name: "3-in-1 curtain",
    name_fr: "Rideau 3 en 1",
    category: "curtains",
    sku: "JHT-RIDEAU-3EN1",
    featured: true,
    price: 9000,
    price_tiers: tiers([[1, null, 9000]]),
    whats_included: "1 three-in-one curtain.",
    whats_included_fr: "1 rideau 3 en 1.",
    description: "A 3-in-1 curtain for the living room or bedroom.",
    description_fr: "Rideau 3 en 1 pour le salon ou la chambre.",
  },
  {
    slug: "large-mosquito-net",
    name: "Large mosquito net",
    name_fr: "Grande moustiquaire",
    category: "mosquito-nets",
    sku: "JHT-MOUSTI-GDE",
    featured: false,
    price: 6500,
    price_tiers: tiers([[1, null, 6500]]),
    whats_included: "1 large mosquito net.",
    whats_included_fr: "1 grande moustiquaire.",
    description: "A large mosquito net for the bedroom.",
    description_fr: "Grande moustiquaire pour la chambre.",
  },
  {
    slug: "medium-mosquito-net",
    name: "Medium mosquito net",
    name_fr: "Moustiquaire taille moyenne",
    category: "mosquito-nets",
    sku: "JHT-MOUSTI-MOY",
    featured: false,
    price: 3500,
    price_tiers: tiers([[1, null, 3500]]),
    whats_included: "1 medium mosquito net.",
    whats_included_fr: "1 moustiquaire taille moyenne.",
    description: "A medium-size mosquito net.",
    description_fr: "Moustiquaire de taille moyenne.",
  },
  {
    slug: "sofa-cover",
    name: "Sofa cover",
    name_fr: "Housse de canapé",
    category: "sofa-covers",
    sku: "JHT-HOUSSE-CANAPE",
    featured: true,
    price: 20000,
    price_tiers: tiers([[1, null, 20000]]),
    whats_included: "1 sofa cover.",
    whats_included_fr: "1 housse de canapé.",
    description: "A sofa cover that refreshes the living room.",
    description_fr: "Housse de canapé pour renouveler le salon.",
  },
  {
    slug: "double-mattress-protector",
    name: "Double mattress protector",
    name_fr: "Protège-matelas 2 places",
    category: "mattress-protectors",
    sku: "JHT-PROTEGE-2P",
    featured: false,
    price: 10000,
    price_tiers: tiers([[1, null, 10000]]),
    whats_included: "1 double mattress protector.",
    whats_included_fr: "1 protège-matelas 2 places.",
    description: "Mattress protector for a double bed.",
    description_fr: "Protège-matelas pour un lit 2 places.",
  },
  {
    slug: "triple-mattress-protector",
    name: "Triple mattress protector",
    name_fr: "Protège-matelas 3 places",
    category: "mattress-protectors",
    sku: "JHT-PROTEGE-3P",
    featured: false,
    price: 11000,
    price_tiers: tiers([[1, null, 11000]]),
    whats_included: "1 triple mattress protector.",
    whats_included_fr: "1 protège-matelas 3 places.",
    description: "Mattress protector for a triple bed.",
    description_fr: "Protège-matelas pour un lit 3 places.",
  },
].map((product) => ({
  ...product,
  image_alts: alts(product.name),
  stock: 5000,
  status: "published",
  delivery_information: "Packed in Douala (Paris Dancing Akwa) and delivered across Cameroon.",
  care_instructions: "Follow the care label. Wash according to the fabric.",
}));
